# Generated by Django 3.0.2 on 2020-12-06 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(default=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='newProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradeId', models.CharField(max_length=30)),
                ('gradeName', models.CharField(max_length=30)),
                ('employeeName', models.CharField(max_length=30)),
                ('quantity', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('varieties', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tea.Variety')),
            ],
        ),
    ]
