# Generated by Django 3.0.2 on 2020-12-07 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('grade_supplied', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tea.Variety')),
            ],
        ),
    ]
