# Generated by Django 3.0.2 on 2020-12-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0002_suppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='Location',
            field=models.CharField(default=True, max_length=30),
        ),
    ]
